#!/usr/bin/env python3
"""Regenerates Sources/PawvisCore/Audio/MP3Tables.swift.

The MP3 encoder needs three normative tables from ISO/IEC 11172-3 (MPEG-1
Audio) Annex B: the Layer III Huffman code tables (B.7), the analysis
window coefficients (C.1) and the long-block scalefactor band boundaries
(B.8). Typing several thousand numbers by hand is how bitstreams go
silently wrong, so this reads them out of a pinned copy of the shine
reference encoder's sources (github.com/toots/shine), which carries the
tables verbatim, and emits Swift. Run it only if the tables file is lost;
the output is committed.

    python3 scripts/make_mp3_tables.py
"""
import re
import sys
import urllib.request
from pathlib import Path

# Pinned so the run is reproducible; the data is the standard's either way.
SHINE_COMMIT = "ab5e3526b64af1a2eaa43aa6f441a7312e013519"
BASE = f"https://raw.githubusercontent.com/toots/shine/{SHINE_COMMIT}/src/lib/"
OUT = Path(__file__).resolve().parent.parent / "Sources/PawvisCore/Audio/MP3Tables.swift"

TABLES = [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 24, 32, 33]


def fetch(name):
    with urllib.request.urlopen(BASE + name) as response:
        return response.read().decode("utf-8")


def parse_array(src, name):
    match = re.search(r"\b" + re.escape(name) + r"\[\]\s*=\s*\{([^}]*)\}", src, re.S)
    if not match:
        raise SystemExit(f"missing {name}")
    return [int(x) for x in re.findall(r"-?\d+", match.group(1))]


def swift_ints(name, typ, values, per=16):
    out = [f"    static let {name}: [{typ}] = ["]
    for i in range(0, len(values), per):
        out.append("        " + ", ".join(str(v) for v in values[i:i + per]) + ",")
    out.append("    ]")
    return "\n".join(out)


def swift_doubles(name, values, per=6):
    out = [f"    static let {name}: [Double] = ["]
    for i in range(0, len(values), per):
        out.append("        " + ", ".join(values[i:i + per]) + ",")
    out.append("    ]")
    return "\n".join(out)


def main():
    huffman = fetch("huffman.c")
    tables = fetch("tables.c")

    codes, lengths = {}, {}
    for n in TABLES:
        codes[n] = parse_array(huffman, f"t{n}HB")
        lengths[n] = parse_array(huffman, f"t{n}l")
        if len(codes[n]) != len(lengths[n]):
            raise SystemExit(f"table {n}: {len(codes[n])} codes vs {len(lengths[n])} lengths")

    window_src = tables[tables.index("shine_enwindow[]"):]
    window = re.findall(r"-?\d+\.\d+", window_src)
    if len(window) != 512:
        raise SystemExit(f"analysis window has {len(window)} taps, expected 512")

    bands_src = re.search(r"shine_scale_fact_band_index\[9\]\[23\]\s*=\s*\{(.*?)\};", tables, re.S).group(1)
    rows = [[int(x) for x in re.findall(r"\d+", r)] for r in re.findall(r"\{([^}]*)\}", bands_src)][:3]
    if any(len(r) != 23 for r in rows):
        raise SystemExit("scalefactor band rows must have 23 boundaries")

    lines = ["""// Generated by scripts/make_mp3_tables.py from the ISO/IEC 11172-3
// (MPEG-1 Audio) Annex B tables — do not edit by hand. The Huffman code
// tables (B.7), the analysis window (C.1, "Coefficients Ci") and the
// scalefactor band boundaries (B.8) are normative data every Layer III
// encoder and decoder carries verbatim; the numbers here were read out of
// the shine reference encoder's copy of them and cross-checked by decoding
// the output with two independent decoders (see MP3EncoderTests and the
// `mp3.*` self-test rows).

/// The normative MPEG-1 Layer III tables.
enum MP3Tables {
    /// Table B.8 (long blocks): scalefactor band boundaries for 44.1, 48
    /// and 32 kHz, in the header's sampling-frequency-index order.
    static let scalefactorBands: [[Int]] = ["""]
    for row in rows:
        lines.append("        [" + ", ".join(str(v) for v in row) + "],")
    lines.append("    ]\n")
    lines.append("    /// Table C.1: the 512 analysis-window coefficients C[i].")
    lines.append(swift_doubles("analysisWindow", window))
    lines.append("")
    for n in TABLES:
        lines.append(f"    // Table B.7, Huffman code table {n}: codes then code lengths.")
        lines.append(swift_ints(f"codes{n}", "UInt16", codes[n]))
        lines.append(swift_ints(f"lengths{n}", "UInt8", lengths[n]))
        lines.append("")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(Path.cwd()) if OUT.is_relative_to(Path.cwd()) else OUT}")


if __name__ == "__main__":
    sys.exit(main())
